name: Build samsung-note8-exynos8895-Kernel
on:
  workflow_dispatch:
  schedule:
      # Run once a week on Sunday at midnight. See http://crontab.guru
      - cron: '0 8 */7 * *'
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu- ARCH=arm64 SUBARCH=arm64 LLVM=1 LLVM_IAS=1 O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        git clone https://github.com/tomxi1997/android-kernel-tools.git clang-aosp --depth=1
        git clone https://github.com/tomxi1997/AnyKernel3.git --depth=1
        rm -rf AnyKernel3/.git
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: Build Kernel-SU
      run: |
       export PATH=$(pwd)/clang-aosp/clang/host/linux-x86/clang-r428724/bin:$(pwd)/clang-aosp/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:$(pwd)/clang-aosp/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       export GKI_ROOT=$(pwd)
       export DRIVER_DIR="$GKI_ROOT/drivers"
       export DRIVER_MAKEFILE=$DRIVER_DIR/Makefile
       export KERNEL_DEFCONFIG=exynos8895-greatlte_defconfig
       git clone -b main https://github.com/tiann/KernelSU.git KernelSU
       ln -sf "$GKI_ROOT/KernelSU/kernel" "$DRIVER_DIR/kernelsu"
       sed -i '$a\obj-y += kernelsu/' "$DRIVER_MAKEFILE"
       echo "CONFIG_KPROBES=y" >> "$GKI_ROOT/arch/${ARCH}/configs/${KERNEL_DEFCONFIG}"
       echo "CONFIG_HAVE_KPROBES=y" >> "$GKI_ROOT/arch/${ARCH}/configs/${KERNEL_DEFCONFIG}"
       echo "CONFIG_KPROBE_EVENTS=y" >> "$GKI_ROOT/arch/${ARCH}/configs/${KERNEL_DEFCONFIG}"
       make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang"
       make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all)
       cp out/arch/arm64/boot/Image.gz AnyKernel3

    - name: Upload Kernel 
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-kernelsu-lineage-20.0-greatlte-${{ steps.get_time.outputs.TIME }}
        path: "AnyKernel3/*"

    - name: Build LXC-Kernel-SU
      run: |
        export PATH=$(pwd)/clang-aosp/clang/host/linux-x86/clang-r428724/bin:$(pwd)/clang-aosp/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:$(pwd)/clang-aosp/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:$PATH
        git clone -b lineage-20.0-lxc_support https://github.com/tomxi1997/android_kernel_samsung_universal8895.git note8 --depth=1
        cd note8
        export ARCH=arm64
        export SUBARCH=arm64
        export GKI_ROOT=$(pwd)
        export DRIVER_DIR="$GKI_ROOT/drivers"
        export DRIVER_MAKEFILE=$DRIVER_DIR/Makefile
        export KERNEL_DEFCONFIG=note8_lxc_defconfig
        git clone -b main https://github.com/tiann/KernelSU.git KernelSU
        ln -sf "$GKI_ROOT/KernelSU/kernel" "$DRIVER_DIR/kernelsu"
        sed -i '$a\obj-y += kernelsu/' "$DRIVER_MAKEFILE"
        echo "CONFIG_KPROBES=y" >> "$GKI_ROOT/arch/${ARCH}/configs/${KERNEL_DEFCONFIG}"
        echo "CONFIG_HAVE_KPROBES=y" >> "$GKI_ROOT/arch/${ARCH}/configs/${KERNEL_DEFCONFIG}"
        echo "CONFIG_KPROBE_EVENTS=y" >> "$GKI_ROOT/arch/${ARCH}/configs/${KERNEL_DEFCONFIG}"
        #make $KERNEL_CMDLINE exynos8895-greatlte_lxc_defconfig CC="ccache clang"
        make $KERNEL_CMDLINE CC="ccache clang" note8_lxc_defconfig
        make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all)
        rm -rf ../AnyKernel3/Image.gz
        cp out/arch/arm64/boot/Image.gz ../AnyKernel3
        cd ..
      

    - name: Upload Kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel-kernelsu-lxc-lineage-20.0-greatlte-${{ steps.get_time.outputs.TIME }}
        path: "AnyKernel3/*"
